services:
  ecosort-edge:
    image: pdec5504/ecosort-edge:latest
    container_name: ecosort-edge
    restart: unless-stopped
    network_mode: "host"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority:ro
    env_file:
      - .env
    environment:
      - DISPLAY=:0
      - XAUTHORITY=/root/.Xauthority
    loggin:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.41
    command: --interval 60 --cleanup
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
